export const provinces = {
    ES: [
      { value: 'Madrid', label: 'Madrid' },
      { value: 'Catalonia', label: 'Cataluña' },
      { value: 'Valencia', label: 'Valencia' },
      { value: 'Andalusia', label: 'Andalucía' },
      { value: 'Basque Country', label: 'País Vasco' },
      { value: 'Galicia', label: 'Galicia' },
      { value: 'Canary Islands', label: 'Islas Canarias' },
      { value: 'Castile and Leon', label: 'Castilla y León' },
      { value: 'Extremadura', label: 'Extremadura' },
      { value: 'Balearic Islands', label: 'Islas Baleares' },
      // Puedes añadir más si es necesario
    ],
    US: [
      { value: 'California', label: 'California' },
      { value: 'Texas', label: 'Texas' },
      { value: 'New York', label: 'New York' },
      { value: 'Florida', label: 'Florida' },
      { value: 'Illinois', label: 'Illinois' },
      { value: 'Pennsylvania', label: 'Pennsylvania' },
      { value: 'Ohio', label: 'Ohio' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'North Carolina', label: 'North Carolina' },
      { value: 'Michigan', label: 'Michigan' },
      // Agrega más estados si es necesario
    ],
    MX: [
      { value: 'Mexico City', label: 'Ciudad de México' },
      { value: 'Jalisco', label: 'Jalisco' },
      { value: 'Nuevo Leon', label: 'Nuevo León' },
      { value: 'Yucatan', label: 'Yucatán' },
      { value: 'Puebla', label: 'Puebla' },
      { value: 'Quintana Roo', label: 'Quintana Roo' },
      { value: 'Oaxaca', label: 'Oaxaca' },
      { value: 'Veracruz', label: 'Veracruz' },
      { value: 'Chihuahua', label: 'Chihuahua' },
      { value: 'Tamaulipas', label: 'Tamaulipas' },
      // Agrega más estados de México si es necesario
    ],
    CA: [
      { value: 'Ontario', label: 'Ontario' },
      { value: 'Quebec', label: 'Quebec' },
      { value: 'British Columbia', label: 'British Columbia' },
      { value: 'Alberta', label: 'Alberta' },
      { value: 'Manitoba', label: 'Manitoba' },
      { value: 'Saskatchewan', label: 'Saskatchewan' },
      { value: 'Nova Scotia', label: 'Nova Scotia' },
      { value: 'New Brunswick', label: 'New Brunswick' },
      { value: 'Newfoundland and Labrador', label: 'Newfoundland and Labrador' },
      { value: 'Prince Edward Island', label: 'Prince Edward Island' },
    ],
    BR: [
      { value: 'São Paulo', label: 'São Paulo' },
      { value: 'Rio de Janeiro', label: 'Rio de Janeiro' },
      { value: 'Minas Gerais', label: 'Minas Gerais' },
      { value: 'Bahia', label: 'Bahia' },
      { value: 'Paraná', label: 'Paraná' },
      { value: 'Rio Grande do Sul', label: 'Rio Grande do Sul' },
      { value: 'Pernambuco', label: 'Pernambuco' },
      { value: 'Ceará', label: 'Ceará' },
      { value: 'Pará', label: 'Pará' },
      { value: 'Santa Catarina', label: 'Santa Catarina' },
    ],
    AR: [
      { value: 'Buenos Aires', label: 'Buenos Aires' },
      { value: 'Córdoba', label: 'Córdoba' },
      { value: 'Santa Fe', label: 'Santa Fe' },
      { value: 'Mendoza', label: 'Mendoza' },
      { value: 'Tucumán', label: 'Tucumán' },
      { value: 'Salta', label: 'Salta' },
      { value: 'Entre Ríos', label: 'Entre Ríos' },
      { value: 'Misiones', label: 'Misiones' },
      { value: 'Chaco', label: 'Chaco' },
      { value: 'Corrientes', label: 'Corrientes' },
    ],
    IN: [
      { value: 'Maharashtra', label: 'Maharashtra' },
      { value: 'Karnataka', label: 'Karnataka' },
      { value: 'Tamil Nadu', label: 'Tamil Nadu' },
      { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
      { value: 'Delhi', label: 'Delhi' },
      { value: 'Gujarat', label: 'Gujarat' },
      { value: 'Rajasthan', label: 'Rajasthan' },
      { value: 'West Bengal', label: 'West Bengal' },
      { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
      { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    ],
    // Agrega más países y provincias según sea necesario
  };
  